using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnnamedOS.services.Utils
{
    public class Converter
    {
        public static string HexToAscii(string hex)
        {
            switch (hex)
            {
                // control character

                case "00":
                    return "NUL";
                case "03":
                    return "ETX"; // end of text
                case "07":
                    return "BEL"; // BEEP sound
                case "08":
                    return "BS";  // Backspace
                case "09":
                    return "HT";  // Horizontal Tab
                case "1B":
                    return "ESC"; // Escape
                case "1C":
                    return "FS";  // File separator

                // basic characters

                case "20":
                    return " ";
                case "21":
                    return "!";
                case "22":
                    return "\"";
                case "23":
                    return "#";
                case "24":
                    return "$";
                case "25":
                    return "%";
                case "26":
                    return "&";
                case "27":
                    return "'";
                case "28":
                    return "(";
                case "29":
                    return ")";
                case "2A":
                    return "*";
                case "2B":
                    return "+";
                case "2C":
                    return ",";
                case "2D":
                    return "-";
                case "2E":
                    return ".";
                case "2F":
                    return "/";
                case "30":
                    return "0";
                case "31":
                    return "1";
                case "32":
                    return "2";
                case "33":
                    return "3";
                case "34":
                    return "4";
                case "35":
                    return "5";
                case "36":
                    return "6";
                case "37":
                    return "7";
                case "38":
                    return "8";
                case "39":
                    return "9";
                case "3A":
                    return ":";
                case "3B":
                    return ";";
                case "3C":
                    return "<";
                case "3D":
                    return "=";
                case "3E":
                    return ">";
                case "3F":
                    return "?";
                case "40":
                    return "@";
                case "41":
                    return "A";
                case "42":
                    return "B";
                case "43":
                    return "C";
                case "44":
                    return "D";
                case "45":
                    return "E";
                case "46":
                    return "F";
                case "47":
                    return "G";
                case "48":
                    return "H";
                case "49":
                    return "I";
                case "4A":
                    return "J";
                case "4B":
                    return "K";
                case "4C":
                    return "L";
                case "4D":
                    return "M";
                case "4E":
                    return "N";
                case "4F":
                    return "O";
                case "50":
                    return "P";
                case "51":
                    return "Q";
                case "52":
                    return "R";
                case "53":
                    return "S";
                case "54":
                    return "T";
                case "55":
                    return "U";
                case "56":
                    return "V";
                case "57":
                    return "W";
                case "58":
                    return "X";
                case "59":
                    return "Y";
                case "5A":
                    return "Z";
                case "5B":
                    return "[";
                case "5C":
                    return "\\";
                case "5D":
                    return "]";
                case "5E":
                    return "^";
                case "5F":
                    return "_";
                case "60":
                    return "`";
                case "61":
                    return "a";
                case "62":
                    return "b";
                case "63":
                    return "c";
                case "64":
                    return "d";
                case "65":
                    return "e";
                case "66":
                    return "f";
                case "67":
                    return "g";
                case "68":
                    return "h";
                case "69":
                    return "i";
                case "6A":
                    return "j";
                case "6B":
                    return "k";
                case "6C":
                    return "l";
                case "6D":
                    return "m";
                case "6E":
                    return "n";
                case "6F":
                    return "o";
                case "70":
                    return "p";
                case "71":
                    return "q";
                case "72":
                    return "r";
                case "73":
                    return "s";
                case "74":
                    return "t";
                case "75":
                    return "u";
                case "76":
                    return "v";
                case "77":
                    return "w";
                case "78":
                    return "x";
                case "79":
                    return "y";
                case "7A":
                    return "z";
                case "7B":
                    return "{";
                case "7C":
                    return "|";
                case "7D":
                    return "}";
                case "7E":
                    return "~";
                case "7F":
                    return "DEL";

                // Extended ASCII
                // Only CP437 supported

                case "80":
                    return "Ç";
                case "81":
                    return "ü";
                case "82":
                    return "é";
                case "83":
                    return "â";
                case "84":
                    return "ä";
                case "85":
                    return "à";
                case "86":
                    return "å";
                case "87":
                    return "ç";
                case "88":
                    return "ê";
                case "89":
                    return "ë";
                case "8A":
                    return "è";
                case "8B":
                    return "ï";
                case "8C":
                    return "î";
                case "8D":
                    return "ì";
                case "8E":
                    return "Ä";
                case "8F":
                    return "Å";
                case "90":
                    return "É";
                case "91":
                    return "æ";
                case "92":
                    return "Æ";
                case "93":
                    return "ô";
                case "94":
                    return "ö";
                case "95":
                    return "ò";
                case "96":
                    return "û";
                case "97":
                    return "ù";
                case "98":
                    return "ÿ";
                case "99":
                    return "Ö";
                case "9A":
                    return "Ü";
                case "9B":
                    return "¢";
                case "9C":
                    return "£";
                case "9D":
                    return "¥";
                case "9E":
                    return "₧";
                case "9F":
                    return "ƒ";
                case "A0":
                    return "á";
                case "A1":
                    return "í";
                case "A2":
                    return "ó";
                case "A3":
                    return "ú";
                case "A4":
                    return "ñ";
                case "A5":
                    return "Ñ";
                case "A6":
                    return "ª";
                case "A7":
                    return "º";
                case "A8":
                    return "¿";
                case "A9":
                    return "⌐";
                case "AA":
                    return "¬";
                case "AB":
                    return "½";
                case "AC":
                    return "¼";
                case "AD":
                    return "¡";
                case "AE":
                    return "«";
                case "AF":
                    return "»";
                case "B0":
                    return "░";
                case "B1":
                    return "▒";
                case "B2":
                    return "▓";
                case "B3":
                    return "│";
                case "B4":
                    return "┤";
                case "B5":
                    return "╡";
                case "B6":
                    return "╢";
                case "B7":
                    return "╖";
                case "B8":
                    return "╕";
                case "B9":
                    return "╣";
                case "BA":
                    return "║";
                case "BB":
                    return "╗";
                case "BC":
                    return "╝";
                case "BD":
                    return "╜";
                case "BE":
                    return "╛";
                case "BF":
                    return "┐";
                case "C0":
                    return "└";
                case "C1":
                    return "┴";
                case "C2":
                    return "┬";
                case "C3":
                    return "├";
                case "C4":
                    return "─";
                case "C5":
                    return "┼";
                case "C6":
                    return "╞";
                case "C7":
                    return "╟";
                case "C8":
                    return "╚";
                case "C9":
                    return "╔";
                case "CA":
                    return "╩";
                case "CB":
                    return "╦";
                case "CC":
                    return "╠";
                case "CD":
                    return "═";
                case "CE":
                    return "╬";
                case "CF":
                    return "╧";
                case "D0":
                    return "╨";
                case "D1":
                    return "╤";
                case "D2":
                    return "╥";
                case "D3":
                    return "╙";
                case "D4":
                    return "╘";
                case "D5":
                    return "╒";
                case "D6":
                    return "╓";
                case "D7":
                    return "╫";
                case "D8":
                    return "╪";
                case "D9":
                    return "┘";
                case "DA":
                    return "┌";
                case "DB":
                    return "█";
                case "DC":
                    return "▄";
                case "DD":
                    return "▌";
                case "DE":
                    return "▐";
                case "DF":
                    return "▀";
                case "E0":
                    return "α";
                case "E1":
                    return "ß";
                case "E2":
                    return "Γ";
                case "E3":
                    return "π";
                case "E4":
                    return "Σ";
                case "E5":
                    return "σ";
                case "E6":
                    return "µ";
                case "E7":
                    return "τ";
                case "E8":
                    return "Φ";
                case "E9":
                    return "Θ";
                case "EA":
                    return "Ω";
                case "EB":
                    return "δ";
                case "EC":
                    return "∞";
                case "ED":
                    return "φ";
                case "EE":
                    return "ε";
                case "EF":
                    return "∩";
                case "F0":
                    return "≡";
                case "F1":
                    return "±";
                case "F2":
                    return "≥";
                case "F3":
                    return "≤";
                case "F4":
                    return "⌠";
                case "F5":
                    return "⌡";
                case "F6":
                    return "÷";
                case "F7":
                    return "≈";
                case "F8":
                    return "°";
                case "F9":
                    return "∙";
                case "FA":
                    return "·";
                case "FB":
                    return "√";
                case "FC":
                    return "ⁿ";
                case "FD":
                    return "²";
                case "FE":
                    return "■";
                case "FF":
                    return "";



                default:
                    return "?";
            }
        }
    }
}
